### ISSUE TITLE
Endless loop of started ready to flight

### ISSUE THREAD

**Issue by vanosten** [hardba11/bourrasque#63]
Hi 

The following I can only reproduce on the Truman carrier or PNHL. The voice message "Started. Ready to Flight" repeats endlessly. This has been the case for several weeks (cannot tell how many). On Windows 10, 2018.3 (next), today's pull from your repository. First start Multiplayer, then Fast Start. It seems to be an issue both at PNHL and on Truman carrier, but not e.g. at LSZR.
Or it is just random (right at a moment with a retest [same versions]) I do not get this error on the Truman ... until I have launched (I.e. I get it once when the start-up has been done, then nothing for a while, and then endlessly after the catapult launch

**Comment by hardba11** [comment]
Hi
I will try to reproduce and debug if necessary
thanks for feedback ;)
