### ISSUE TITLE
Questions about the autopilot

### ISSUE THREAD

**Issue by valtsu41** [hardba11/bourrasque#84]
Hi,
Is it possible for the autopilot to do GPS routes or ILS approaches somehow? I did not get them to work when I tried to.

**Comment by SammySkycrafts** [comment]
I cant seem to find Any AP related controls, and starting it from in the FG Autopilot > Autopilot Settings doesnt seem to work either?

**Comment by hardba11** [comment]
hello !
it's not possible. the autopilot is basic.
may be later, if I have enough time, I will improve it ;)
