### ISSUE TITLE
Detecting multiplayer aircraft in cold and dark

### ISSUE THREAD

**Issue by sryu1** [hardba11/bourrasque#92]
<img width="960" alt="20221126_152018" src="https://user-images.githubusercontent.com/95025816/204087257-9ea6609c-9874-41cf-a401-38248587a9ca.png">
<img width="960" alt="20221126_151902" src="https://user-images.githubusercontent.com/95025816/204087264-159899bc-fdd4-4417-a481-f997c2c50904.png">
Is this because it's a helmet hud? or is it a bug?

**Comment by sryu1** [comment]
I could also detect a mp copilot on helmet hud...

**Comment by hardba11** [comment]
It is not a bug, it's a feature.
Target-positions is not an helmet hud but a simulation's "helper" because in real life, it's easier to perciev objects, distances and relative speed.

**Comment by sryu1** [comment]
Is there a feature to turn this off? I sometimes find this a bit annoying in multiplayer. Also, I think showing the mp copilot is a bit unnecessary...
